### PR TITLE
js: 79 chars, no r/e\g/e\x

### PR DESCRIPTION
**Pull request by eranws**
in 79 chars:
`K=(s,r="",c=1)=>[...s].reduce((_,v,i,a)=>(v==a[i+1]?[0,c++]:[r+=c+v,c=1]),0)[0]`

### CODE REVIEW

**Comment by eranws** [comment]
72 chars:
`K=(s,r="",c=1)=>[...s].map((v,i,a)=>v==a[i+1]?c++:[r+=c+v,c=1]).pop()[0]`

**Comment by eranws** [comment]
70 chars:
`K=(s,r="",c=1)=>[...s].map((v,i)=>v==s[i+1]?c++:[r+=c+v,c=1]).pop()[0]`

**Comment by otobrglez** [comment]
Hey @eranws! 👋 

Thank you for your time and effort! I really enjoyed reading your solutions! Hope that you'll also read other solutions yourself and be inspired in your future work and explorations.

I would also like to say that the [giant Chameleon sculpture](http://come-million.com/) is trippy, and I love it! ;)

sincerely,

- Oto

**Comment by eranws** [comment]
Hi @otobrglez !
Thanks for creating this fun challenge, it has more to it than it seems at first :)
I'm glad you liked the chameleon!

**Pull request merged**
