### PR TITLE
Working Red Nix/Docker setup + solutions

### PR DESCRIPTION
**Pull request by InvoiceFox**
Red scripts work via rebolek/red docker hub image. Makefile is fixed so all red scripts get executer with Nix command: 

    nix-shell shell.nix --run "make red-docker" 

I collected and tested all Red solutions, from other PR-s and Red gitter chat. I hope it's OK, but I wanted to see all Red solutions work.

### CODE REVIEW

**Comment by otobrglez** [comment]
Thank you @rebolek, @InvoiceFox / @jankom, @greggirwin and @hiiamboris for your effort, not just on the solution but also on getting the things around it to work. I hope that this solution will encourage people to explore Red & Rebol. 

Thank you!

**Comment by loziniak** [comment]
Another possible solution :-)
https://github.com/exercism/red/blob/3793625ab39ab2d64a6628b28c77258a33f3864d/exercises/practice/run-length-encoding/.meta/example.red

**Comment by otobrglez** [comment]
O, wow @loziniak! It looks lovely!

Might I please ask u to add it to the project?

**Comment by greggirwin** [comment]
Really clean @loziniak.

**Pull request merged**
