### PR TITLE
Added Red solution

### PR DESCRIPTION
**Pull request by rebolek**
This is a solution written in [Red language](https://github.com/red/red). It’s a one-liner but split into commented multiple lines for easier understanding. As a bonus, I added decompression also.

### CODE REVIEW

**Comment by otobrglez** [comment]
Thank you @rebolek for your effort and submission!

Please give me some time to add `red` support to the "build system". I've found out that it's unsupported on my darwin arch. 

Epic!

**Comment by otobrglez** [comment]
@rebolek How do I run this thing? :) Assuming that I have rebol/red installed?

**Comment by otobrglez** [comment]
I've experimented with this. Without luck. ;|

```bash
docker run -ti --rm -v $PWD:/tmp/app --entrypoint nix-shell nixos/nix -p red \
  --run "red -r /tmp/app/src/red/compress.red"
```

Screenshot 2022-02-01 at 16 53 00

**Comment by rebolek** [comment]
@otobrglez your command should be `"red /tmp/app/src/red/compress.red"` without `-r`. Anyway, if I try it, it still complains it can’t find the file. It has something to do with Docker path mapping. I’m not an expert on Docker but I try to find a solution and let you know.

**Comment by otobrglez** [comment]
@rebolek can you please explain this cryptic error message to me please?

```bash
$ docker run -ti -v $PWD:/app --entrypoint /bin/bash kskarthik/redlang:0.6.4 /app/src/red/run-red.sh
+ cd /app/src/red
+ red compress.red
Compiling compression library...
Compiling Red console...
*** Syntax Error: invalid value at "^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@"
*** Where: do
*** Stack: load
```

This is me trying to use [kskarthik/redlang:0.6.4](https://hub.docker.com/r/kskarthik/redlang) docker image with Red with a bash script to overcome [this issue](https://github.com/red/red/issues/3562). 

The `run-red.sh` looks like this

```bash
#!/usr/bin/env bash
set -ex

cd /app/src/red && red compress.red
```

Thank you!

[PR for work on adding support here.](https://github.com/otobrglez/compression-puzzle/pull/21)

**Comment by loziniak** [comment]
Perhaps you could find useful this repo as an example: https://github.com/exercism/red-test-runner/

**Comment by rebolek** [comment]
@otobrglez `^@` is zero, so it's somehow reading an empty file.
@hiiamboris wrote: "This looks like a problem with 32-bit file system driver. I got smth like that on WSL2 when reading files from NTFS partitions."

**Comment by rebolek** [comment]
@otobrglez 

Ok, I've got it, removing `-t` is enough, the script works then, here's the proper command (assuming you are in the repo's root):

```
docker run -ti --rm -v $PWD:/tmp/app --entrypoint nix-shell nixos/nix -p red \
  --run "red -r /tmp/app/src/red/compress.red"
```
However, there is no output from the script as it only throws an error if the assertion failed and outputs nothing if there's no error.

**Comment by otobrglez** [comment]
Closing in favour of [this PR](https://github.com/otobrglez/compression-puzzle/pull/39)

**Pull request closed without merging**
